version: 0.0

os: linux

files:
  - source: ./
    destination: /opt/bitnami/apps/django/django_projects/Project/

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/applicationstart.sh
